TEAM_ALIASES = {
    "arizona": "Arizona Diamondbacks",
    "diamondbacks": "Arizona Diamondbacks",
    "athletics": "Athletics",
    "a's": "Athletics",
    "as": "Athletics",
    "atlanta": "Atlanta Braves",
    "ny yankees": "New York Yankees",
    "yankees": "New York Yankees",
    "nyy": "New York Yankees",
    "new york y": "New York Yankees",
    "baltimore": "Baltimore Orioles",
    "boston": "Boston Red Sox",
    "chicago c": "Chicago Cubs",
    "chicago white sox": "Chicago White Sox",
    "chicago w": "Chicago White Sox",
    "chicago ws": "Chicago White Sox",
    "cincinnati": "Cincinnati Reds",
    "cleveland": "Cleveland Guardians",
    "colorado": "Colorado Rockies",
    "detroit": "Detroit Tigers",
    "houston": "Houston Astros",
    "kansas city": "Kansas City Royals",
    "la dodgers": "Los Angeles Dodgers",
    "dodgers": "Los Angeles Dodgers",
    "lad": "Los Angeles Dodgers",
    "los angeles d": "Los Angeles Dodgers",
    "los angeles a": "Los Angeles Angels",
    "la angels": "Los Angeles Angels",
    "miami": "Miami Marlins",
    "milwaukee": "Milwaukee Brewers",
    "minnesota": "Minnesota Twins",
    "nym": "New York Mets",
    "ny mets": "New York Mets",
    "mets": "New York Mets",
    "new york m": "New York Mets",
    "philadelphia": "Philadelphia Phillies",
    "pittsburgh": "Pittsburgh Pirates",
    "san diego": "San Diego Padres",
    "san francisco": "San Francisco Giants",
    "seattle": "Seattle Mariners",
    "st louis": "St. Louis Cardinals",
    "st louis cardinals": "St. Louis Cardinals",
    "tampa bay": "Tampa Bay Rays",
    "texas": "Texas Rangers",
    "toronto": "Toronto Blue Jays",
    "washington": "Washington Nationals",
    "atl": "Atlanta Braves",
    "braves": "Atlanta Braves",
}
